name: Convert GeoGaga DAT to Mihomo Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Download GeoGaga DAT files
        run: |
          mkdir -p temp rules txt
          curl -fsSL -o temp/geosite.dat https://github.com/bratishkadrugoimamysynishka/geogaga-client-flavor/releases/latest/download/geosite.dat
          curl -fsSL -o temp/geoip.dat https://github.com/bratishkadrugoimamysynishka/geogaga-client-flavor/releases/latest/download/geoip.dat

      - name: Install v2dat
        run: |
          curl -fsSL -o v2dat https://github.com/returnyx/v2dat/releases/download/v20240712/v2dat_20240712_amd64
          chmod +x v2dat

      - name: Unpack DAT to TXT
        run: |
          ./v2dat unpack geosite -d ./txt -f geogaga-block temp/geosite.dat || true
          ./v2dat unpack geosite -d ./txt -f geogaga-direct temp/geosite.dat || true
          ./v2dat unpack geosite -d ./txt -f geogaga-proxy temp/geosite.dat || true
          ./v2dat unpack
