name: Convert GeoGaga Client DAT to Mihomo Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download GeoGaga DAT files
        run: |
          mkdir -p temp rules
          curl -sSL -o temp/geosite.dat https://github.com/bratishkadrugoimamysynishka/geogaga-client-flavor/releases/latest/download/geosite.dat
          curl -sSL -o temp/geoip.dat https://github.com/bratishkadrugoimamysynishka/geogaga-client-flavor/releases/latest/download/geoip.dat

      - name: Install v2dat
        run: |
          curl -sSL -o v2dat.tar.gz https://github.com/uraimo/v2dat/releases/download/v1.6.0/v2dat_1.6.0_Linux_x86_64.tar.gz
          tar -xvf v2dat.tar.gz v2dat
          chmod +x v2dat

      - name: Unpack DAT to YAML
        run: |
          # Флаг -f передает список тегов. Если категории нет в IP, || true предотвратит остановку сборки
          ./v2dat unpack geosite -o ./rules -f geogaga-block temp/geosite.dat || true
          ./v2dat unpack geosite -o ./rules -f geogaga-direct temp/geosite.dat || true
          ./v2dat unpack geosite -o ./rules -f geogaga-proxy temp/geosite.dat || true

          ./v2dat unpack geoip -o ./rules -f geogaga-block temp/geoip.dat || true
          ./v2dat unpack geoip -o ./rules -f geogaga-direct temp/geoip.dat || true
          ./v2dat unpack geoip -o ./rules -f geogaga-proxy temp/geoip.dat || true

      - name: Commit & Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add rules/*.yaml
          git status
          git diff-index --quiet HEAD || git commit -m "Auto-update GeoGaga Client rules [skip ci]"
          git push
